language: ruby
rvm:
  - 2.6
cache: bundler

branches:
  only:
    - development

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: 
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  cleanup: true
  target_branch: master
  on:
    branch: development