title: Hummus Hacks
email: hummushacks@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The world's first and only Hummus themed Hackathon!
baseurl: ""
url: "https://hummushacks.github.io"
github_username:  HummusHacks

theme: minima

plugins:
   - jekyll-sitemap

include: 
  - _pages

exclude:
  - README.md
  - vendor

defaults: 
  - scope:
      path: "_pages"
    values:
      layout: "default"